-- DROP TABLE PLAYDATA.user IF EXISTS;

CREATE TABLE bookmark (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    time_created DATETIME NOT NULL,
    url TEXT NOT NULL,
    stamp DATETIME NOT NULL,
    rev_no INTEGER NOT NULL
);
