DROP TABLE PLAYDATA.user IF EXISTS;

CREATE TABLE PLAYDATA.user (
    userId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    lang TEXT NOT NULL,
    secretNumber INTEGER NOT NULL,
    stamp DATETIME NOT NULL,
    revNo INTEGER NOT NULL
);

CREATE INDEX PLAYDATA.userId ON user (userId);
